#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Command\ConsumerCommand;
use App\Command\ProducerCommand;
use Symfony\Component\Console\Application;
use App\Command\ListTopicsCommand;

$application = new Application();

$application->add(new ListTopicsCommand());
$application->add(new ProducerCommand());
$application->add(new ConsumerCommand());

$application->run();
